apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ required "AWS_ACCESS_KEY_ID is required!" .Values.awsKeyID | printf "%v" | b64enc}}
  AWS_SECRET_ACCESS_KEY: {{ required "AWS_SECRET_ACESS_KEY is required!" .Values.awsSecretKey | printf "%v" | b64enc }}
  SQS_QUEUE_URL: {{ required "SQS Queue URL is required!" .Values.sqsQueueURL }}
